import type { TermItem } from '../components/TermSection/TermSection';

export const experience: TermItem[] = [
  { name: 'Technical Founder', dim: 'Silky', href: '#/experience/silky', meta: 'client discovery · Python · Jun 2026 - now', line: 'Automating listing creation from a factory spreadsheet and apparel photos for TikTok Shop. Deployed with a real client processing 900 SKUs a year, from the first message to a working tool in four versions over three months.' },
  { name: 'AI Engineer Fellow', dim: 'Handshake', href: '#/experience/handshake', meta: 'agent-run pipelines · Apr 2026 - now', line: 'Evaluation work on frontier AI models at Handshake AI: benchmark tasks, golden solutions, adversarial tests, and head-to-head model comparisons. My main project was an agent pipeline that builds terminal benchmark tasks and hardens them until the models fail, with over 30 tasks accepted.' },
  { name: 'Technical Founder', dim: 'Recallia', href: '#/experience/recallia', meta: 'event-driven architecture · Jun 2025 - Jun 2026', line: 'AI reflection app on iOS. A Sunday Letter that connects a week of small moments. ~200 users, a year of founder lessons.' },
  { name: 'Software Engineer Intern', dim: 'TU Crete', href: '#/experience/tu-crete', meta: 'inter-process communication · Electron · Jun - Aug 2025', line: "Desktop app for Wi-Fi diagnosis from a packet capture: how crowded the channel is, how fast a link runs, and why, without a speed test occupying the channel. On traces around Chania the density score tracked retry rate at r = 0.75 on 5 GHz." },
  { name: 'Full Stack Engineer', dim: 'Memoir Photos', href: '#/experience/memoir', meta: 'Feb – May 2025', line: 'Photo processing migrated to async Celery/Redis — ~80% faster, live WebSocket status.' },
  { name: 'Product Engineer', dim: 'USC Heat Lab', href: '#/experience/heat-lab', meta: 'extensible flows · React · Aug 2024 - Feb 2025', line: "Web app for a USC lab's language tests of bilingual children, with every answer and recording collected for the researchers. I rebuilt it into a shell that a new task type plugs into, on a shared component set, and deployed it." },
];
